name: Deploy Front-End

on:
  workflow_dispatch:

env:                                            # <<-- Add environment variables here
  REACT_APP_API_URL: ${{ secrets.API_URL }}     # <<-- referencing the GitHub secrets
  REACT_APP_API_KEY: ${{ secrets.API_KEY }}     # <<-- created in Step 2
jobs:
  build:
    runs-on: windows-latest

    defaults:                                             # <<-- Add default working directory
      run:                                                # <<-- here to ensure deployment 
        working-directory: ./Humongous.Healthcare.Web/    # <<-- targets correct path.
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
